/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORT1_8 (coord A1), P1_8/J9[32]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT1_9 (coord B1), P1_9/J9[30]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT0_2 (coord B16), P0_2/SWO/J23[6]/D16[4]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_SWD_SWO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_SWD_SWO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_SWD_SWO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#define PCR_DSE_dse1 0x01u /*!<@brief Drive Strength Enable: High */
#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */
#define PCR_ODE_ode1 0x01u /*!<@brief Open Drain Enable: Enables */
#define PCR_PS_ps1 0x01u   /*!<@brief Pull Select: Enables internal pullup resistor */

/*! @name PORT3_2 (coord D15), CAM_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_SDA_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_SDA_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_SDA_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT3_3 (coord D16), CAM_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_SCL_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_SCL_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_SCL_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT2_2 (coord H3), CAM_XCLK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_XCLK_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_XCLK_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_XCLK_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT0_5 (coord A14), CAM_PCLK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_PCLK_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_PCLK_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_PCLK_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT0_4 (coord B14), CAM_VSYNC
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_VSYNC_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_VSYNC_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_VSYNC_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORT0_11 (coord B11), CAM_HSYNC
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_HSYNC_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_HSYNC_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_HSYNC_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT1_11 (coord D3), CAM_D7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITCAMERAPINS_CAM_D7_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D7_GPIO_PIN 11U              /*!<@brief GPIO pin number */
#define BOARD_INITCAMERAPINS_CAM_D7_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_D7_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D7_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_D7_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT1_10 (coord C3), CAM_D6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITCAMERAPINS_CAM_D6_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D6_GPIO_PIN 10U              /*!<@brief GPIO pin number */
#define BOARD_INITCAMERAPINS_CAM_D6_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_D6_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D6_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_D6_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT3_5 (coord G14), CAM_D5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITCAMERAPINS_CAM_D5_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D5_GPIO_PIN 5U              /*!<@brief GPIO pin number */
#define BOARD_INITCAMERAPINS_CAM_D5_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_D5_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D5_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_D5_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_4 (coord F14), CAM_D4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITCAMERAPINS_CAM_D4_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D4_GPIO_PIN 4U              /*!<@brief GPIO pin number */
#define BOARD_INITCAMERAPINS_CAM_D4_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_D4_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D4_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_D4_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT1_7 (coord A2), CAM_D3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITCAMERAPINS_CAM_D3_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D3_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITCAMERAPINS_CAM_D3_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_D3_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D3_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_D3_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT1_6 (coord B2), CAM_D2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITCAMERAPINS_CAM_D2_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D2_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITCAMERAPINS_CAM_D2_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_D2_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D2_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_D2_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT1_5 (coord B3), CAM_D1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITCAMERAPINS_CAM_D1_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D1_GPIO_PIN 5U              /*!<@brief GPIO pin number */
#define BOARD_INITCAMERAPINS_CAM_D1_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_D1_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D1_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_D1_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT1_4 (coord A4), CAM_D0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITCAMERAPINS_CAM_D0_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D0_GPIO_PIN 4U              /*!<@brief GPIO pin number */
#define BOARD_INITCAMERAPINS_CAM_D0_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_D0_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_D0_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_D0_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT1_19 (coord G5), CAM_RST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITCAMERAPINS_CAM_RST_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_RST_GPIO_PIN 19U              /*!<@brief GPIO pin number */
#define BOARD_INITCAMERAPINS_CAM_RST_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_RST_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_RST_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_RST_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT1_18 (coord G4), CAM_PDWN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITCAMERAPINS_CAM_PDWN_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_PDWN_GPIO_PIN 18U              /*!<@brief GPIO pin number */
#define BOARD_INITCAMERAPINS_CAM_PDWN_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_CAM_PDWN_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_CAM_PDWN_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_CAM_PDWN_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORT3_18 (coord K16), SMARTDMA_DEBUGIO
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITCAMERAPINS_SMARTDMA_DEBUGIO_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITCAMERAPINS_SMARTDMA_DEBUGIO_GPIO_PIN 18U              /*!<@brief GPIO pin number */
#define BOARD_INITCAMERAPINS_SMARTDMA_DEBUGIO_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITCAMERAPINS_SMARTDMA_DEBUGIO_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCAMERAPINS_SMARTDMA_DEBUGIO_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITCAMERAPINS_SMARTDMA_DEBUGIO_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCameraPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
